-- This file is generated by automatic tools.
library ieee;
use ieee.std_logic_1164.all;
use work.eecs361.all;
use work.eecs361_gates.all;

entity decode is
	port(
		ins: in std_logic_vector(31 downto 0);
		regS: out std_logic_vector(4 downto 0);
		regT: out std_logic_vector(4 downto 0);
		regD: out std_logic_vector(4 downto 0);
		imm: out std_logic_vector(15 downto 0);
		opcode: out std_logic_vector(5 downto 0);
		func: out std_logic_vector(5 downto 0);
		shamt: out std_logic_vector(31 downto 0)
	);
end decode;

architecture structural of decode is
begin
	regS <= ins(25 downto 21);
	regT <= ins(20 downto 16);
	regD <= ins(15 downto 11);
	imm  <= ins(15 downto 0);
	opcode <= ins(31 downto 26);
	func <= ins(5 downto 0);
	shamt <= "000000000000000000000000000"&ins(10 downto 6);
	
end structural;
