-- This file is generated by automatic tools.
library ieee;
use ieee.std_logic_1164.all;
use work.eecs361.all;
use work.eecs361_gates.all;

entity dff_32 is
	port(
		clk	: in  std_logic;
		d	: in  std_logic_vector(31 downto 0);
		q	: out std_logic_vector(31 downto 0)
	);
end dff_32;

architecture behavioral of dff_32 is
begin
	dffr0: dffr port map (clk,d(0),q(0));
    dffr1: dffr port map (clk,d(1),q(1));
    dffr2: dffr port map (clk,d(2),q(2));
    dffr3: dffr port map (clk,d(3),q(3));
    dffr4: dffr port map (clk,d(4),q(4));
    dffr5: dffr port map (clk,d(5),q(5));
    dffr6: dffr port map (clk,d(6),q(6));
    dffr7: dffr port map (clk,d(7),q(7));
    dffr8: dffr port map (clk,d(8),q(8));
    dffr9: dffr port map (clk,d(9),q(9));
    dffr10: dffr port map (clk,d(10),q(10));
    dffr11: dffr port map (clk,d(11),q(11));
    dffr12: dffr port map (clk,d(12),q(12));
    dffr13: dffr port map (clk,d(13),q(13));
    dffr14: dffr port map (clk,d(14),q(14));
    dffr15: dffr port map (clk,d(15),q(15));
    dffr16: dffr port map (clk,d(16),q(16));
    dffr17: dffr port map (clk,d(17),q(17));
    dffr18: dffr port map (clk,d(18),q(18));
    dffr19: dffr port map (clk,d(19),q(19));
    dffr20: dffr port map (clk,d(20),q(20));
    dffr21: dffr port map (clk,d(21),q(21));
    dffr22: dffr port map (clk,d(22),q(22));
    dffr23: dffr port map (clk,d(23),q(23));
    dffr24: dffr port map (clk,d(24),q(24));
    dffr25: dffr port map (clk,d(25),q(25));
    dffr26: dffr port map (clk,d(26),q(26));
    dffr27: dffr port map (clk,d(27),q(27));
    dffr28: dffr port map (clk,d(28),q(28));
    dffr29: dffr port map (clk,d(29),q(29));
    dffr30: dffr port map (clk,d(30),q(30));
    dffr31: dffr port map (clk,d(31),q(31));
end behavioral;